# Generated by Django 4.0.1 on 2022-02-23 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('empleo', models.CharField(max_length=100)),
                ('empleos_disponibles', models.IntegerField()),
                ('enlace', models.URLField()),
                ('imagen', models.ImageField(null=True, upload_to='empleo')),
                ('empresa', models.CharField(max_length=100)),
                ('sueldo', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
