# Generated by Django 4.0.1 on 2022-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcorona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleo',
            name='empleos_disponibles',
            field=models.IntegerField(null=True),
        ),
    ]
